// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://roncfnvmbvymjtjmqeyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvbmNmbnZtYnZ5bWp0am1xZXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2MjA5NzQsImV4cCI6MjA1NjE5Njk3NH0.0T3ULnpe4BVrhIC2MR7g23nl3ls0lYieZzrdMKWrepE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      storageKey: 'marine-data-auth',
      autoRefreshToken: true,
      detectSessionInUrl: true
    },
    global: {
      headers: {
        'X-Client-Info': 'marine-data-minder-android'
      }
    },
    realtime: {
      params: {
        eventsPerSecond: 2
      }
    }
  }
);